# Generated by Django 5.2.7 on 2025-10-31 21:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l_atelier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dni',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_dni', message='No es un número de documento válido', regex='^\\d{7,10}$')], verbose_name='Cédula ciudadanía'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_phonenumber', message='No es un número de teléfono válido', regex='^(3|6)\\d{9}$')], verbose_name='Número teléfono'),
        ),
    ]
